server:
    port: 8080

jwt:
    secret: "test"

spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: api-gateway
    cloud:
      kubernetes:
        reload:
            enabled: false
            url-expression: "uri+'/'"
        discovery:
            enabled: false
            locator:
                enabled: false
                url-expression: "http://'+serviceId+':'+getPort()"
                lower-case-service-id: true

